"""Changing barcode data type

Revision ID: 19f98a104a04
Revises: 41acee4e5090
Create Date: 2023-07-01 22:25:08.999422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f98a104a04'
down_revision = '41acee4e5090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.alter_column('barcode_no',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
