"""Modifying size columns in the database

Revision ID: 24afb2904f26
Revises: e5edc07088af
Create Date: 2023-07-06 13:05:16.035593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24afb2904f26'
down_revision = 'e5edc07088af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_string', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('size_no', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_shirts_size')
        batch_op.create_index(batch_op.f('ix_shirts_size_no'), ['size_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_shirts_size_string'), ['size_string'], unique=False)
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_index(batch_op.f('ix_shirts_size_string'))
        batch_op.drop_index(batch_op.f('ix_shirts_size_no'))
        batch_op.create_index('ix_shirts_size', ['size'], unique=False)
        batch_op.drop_column('size_no')
        batch_op.drop_column('size_string')

    # ### end Alembic commands ###
