"""Adding images fields

Revision ID: 41acee4e5090
Revises: 5eb7e7d59dc9
Create Date: 2023-07-01 21:44:04.576748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41acee4e5090'
down_revision = '5eb7e7d59dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("image", ['image'])

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("image", ['image'])

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("image", ['image'])

    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("image", ['image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
