"""Adding men's collection

Revision ID: 5eb7e7d59dc9
Revises: 8152c2d1f8f1
Create Date: 2023-06-29 00:28:55.856788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb7e7d59dc9'
down_revision = '8152c2d1f8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menscollection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jeans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.Column('menscollection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menscollection_id'], ['menscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jeans_barcode_no'), ['barcode_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_jeans_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_jeans_size'), ['size'], unique=False)

    op.create_table('shirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.Column('menscollection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menscollection_id'], ['menscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shirts_barcode_no'), ['barcode_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_shirts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_shirts_size'), ['size'], unique=False)

    op.create_table('trousers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.Column('menscollection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menscollection_id'], ['menscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trousers_barcode_no'), ['barcode_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_trousers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trousers_size'), ['size'], unique=False)

    op.create_table('tshirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.Column('menscollection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menscollection_id'], ['menscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tshirts_barcode_no'), ['barcode_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_tshirts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tshirts_size'), ['size'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tshirts_size'))
        batch_op.drop_index(batch_op.f('ix_tshirts_name'))
        batch_op.drop_index(batch_op.f('ix_tshirts_barcode_no'))

    op.drop_table('tshirts')
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trousers_size'))
        batch_op.drop_index(batch_op.f('ix_trousers_name'))
        batch_op.drop_index(batch_op.f('ix_trousers_barcode_no'))

    op.drop_table('trousers')
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shirts_size'))
        batch_op.drop_index(batch_op.f('ix_shirts_name'))
        batch_op.drop_index(batch_op.f('ix_shirts_barcode_no'))

    op.drop_table('shirts')
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jeans_size'))
        batch_op.drop_index(batch_op.f('ix_jeans_name'))
        batch_op.drop_index(batch_op.f('ix_jeans_barcode_no'))

    op.drop_table('jeans')
    op.drop_table('menscollection')
    # ### end Alembic commands ###
