"""adding models

Revision ID: 66224f0f8f46
Revises: 99a50e429313
Create Date: 2023-07-24 18:23:50.014227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66224f0f8f46'
down_revision = '99a50e429313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blouse_w',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('womenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dress_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('childrenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['childrenscollection'], ['childrenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dress_w',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('womenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jeans_w',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('womenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfumes_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('accessories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessories'], ['accessories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shirts_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('childrenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['childrenscollection'], ['childrenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoes_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('accessories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessories'], ['accessories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shorts_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('childrenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['childrenscollection'], ['childrenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trouser_w',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('womenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tshirts_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('barcode_no', sa.String(length=20), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('childrenscollection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['childrenscollection'], ['childrenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watches_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('accessories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessories'], ['accessories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blouse')
    op.drop_table('dress')
    with op.batch_alter_table('womenscollection', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('womenscollection', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.create_table('dress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('barcode_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('womenscollection', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blouse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('barcode_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('womenscollection', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['womenscollection'], ['womenscollection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('watches_a')
    op.drop_table('tshirts_c')
    op.drop_table('trouser_w')
    op.drop_table('shorts_c')
    op.drop_table('shoes_a')
    op.drop_table('shirts_c')
    op.drop_table('perfumes_a')
    op.drop_table('jeans_w')
    op.drop_table('dress_w')
    op.drop_table('dress_c')
    op.drop_table('blouse_w')
    # ### end Alembic commands ###
