"""Adding women collection categories

Revision ID: 99a50e429313
Revises: fee8ba1ab8a3
Create Date: 2023-07-19 10:25:59.813864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a50e429313'
down_revision = 'fee8ba1ab8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.drop_constraint('image', type_='unique')

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_constraint('image', type_='unique')

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_constraint('image', type_='unique')

    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.drop_constraint('image', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.create_unique_constraint('image', ['image'])

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.create_unique_constraint('image', ['image'])

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.create_unique_constraint('image', ['image'])

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.create_unique_constraint('image', ['image'])

    # ### end Alembic commands ###
