"""Correcting backref

Revision ID: e17ae183dafd
Revises: 66224f0f8f46
Create Date: 2023-07-24 18:31:45.189357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17ae183dafd'
down_revision = '66224f0f8f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blouse_w', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))

    with op.batch_alter_table('dress_w', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))

    with op.batch_alter_table('jeans_w', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))

    with op.batch_alter_table('perfumes_a', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))

    with op.batch_alter_table('shoes_a', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))

    with op.batch_alter_table('trouser_w', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))

    with op.batch_alter_table('watches_a', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches_a', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('trouser_w', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    with op.batch_alter_table('shoes_a', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('perfumes_a', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('image_name')
        batch_op.drop_column('image')

    with op.batch_alter_table('jeans_w', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    with op.batch_alter_table('dress_w', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    with op.batch_alter_table('blouse_w', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
