"""Modifying size columns in the database

Revision ID: e5edc07088af
Revises: 21a6332694e4
Create Date: 2023-07-06 13:03:56.585122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5edc07088af'
down_revision = '21a6332694e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_string', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('size_no', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_jeans_size')
        batch_op.create_index(batch_op.f('ix_jeans_size_no'), ['size_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_jeans_size_string'), ['size_string'], unique=False)
        batch_op.drop_column('size')

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_string', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('size_no', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_trousers_size')
        batch_op.create_index(batch_op.f('ix_trousers_size_no'), ['size_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_trousers_size_string'), ['size_string'], unique=False)
        batch_op.drop_column('size')

    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_string', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('size_no', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_tshirts_size')
        batch_op.create_index(batch_op.f('ix_tshirts_size_no'), ['size_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_tshirts_size_string'), ['size_string'], unique=False)
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tshirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tshirts_size_string'))
        batch_op.drop_index(batch_op.f('ix_tshirts_size_no'))
        batch_op.create_index('ix_tshirts_size', ['size'], unique=False)
        batch_op.drop_column('size_no')
        batch_op.drop_column('size_string')

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_index(batch_op.f('ix_trousers_size_string'))
        batch_op.drop_index(batch_op.f('ix_trousers_size_no'))
        batch_op.create_index('ix_trousers_size', ['size'], unique=False)
        batch_op.drop_column('size_no')
        batch_op.drop_column('size_string')

    with op.batch_alter_table('jeans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_index(batch_op.f('ix_jeans_size_string'))
        batch_op.drop_index(batch_op.f('ix_jeans_size_no'))
        batch_op.create_index('ix_jeans_size', ['size'], unique=False)
        batch_op.drop_column('size_no')
        batch_op.drop_column('size_string')

    # ### end Alembic commands ###
